services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend
    env_file: .env
    ports:
      - 8001:8001
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
    
  frontend:
    container_name: frontend
    env_file: .env
    build: ./frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: nginx:1.27.2
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pg_data:
  static:
  media:
