services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
    
  frontend:
    container_name: frontend
    env_file: .env
    build: ./frontend
    command: cp -r /app/build/. /frontend_static/
    # command: ["sh", "-c", "cp -r /app/build/. /usr/share/nginx/html && tail -f /dev/null"]
    volumes:
      - static:/frontend_static
      
  nginx:
    container_name: nginx
    build: ./nginx
    env_file: .env
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media

volumes:
  pg_data:
  static:
  media: