MAX_LENGTH_EMAIL = 254
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_NAME = 150
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGHT_TAG = 32
MAX_LENGTH_UNIT = 64
MIN_INGREDIENT_AMOUNT = 1
MIN_COOKING_TIME = 1
QUICK_COOKING = 15
MEDIUM_COOKING = 40
LONG_COOKING = 10**10
COOKING_TIME_FILTERS = {
    'Быстрые': (MIN_COOKING_TIME, QUICK_COOKING),
    'Средние': (QUICK_COOKING, MEDIUM_COOKING),
    'Долгие': (MEDIUM_COOKING, LONG_COOKING)
}
