# Generated by Django 5.1.1 on 2024-10-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_cooking_time_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeshortlink',
            options={'verbose_name': 'короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='short_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Короткий код'),
        ),
    ]
