# Generated by Django 5.1.1 on 2024-10-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/images/', verbose_name='Аватар'),
        ),
    ]
