# Generated by Django 5.1.1 on 2024-09-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_favoriterecipe_user_alter_shoppingrecipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Идентификатор для короткой ссылки'),
        ),
    ]
