# Generated by Django 5.1.1 on 2024-10-08 11:02

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_member_email_alter_member_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[recipes.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
