# Generated by Django 5.1.1 on 2024-09-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_favoriterecipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingrecipe',
            name='shopping_recipe',
        ),
        migrations.RemoveField(
            model_name='shoppingrecipe',
            name='user',
        ),
        migrations.DeleteModel(
            name='FavoriteRecipe',
        ),
        migrations.DeleteModel(
            name='ShoppingRecipe',
        ),
    ]
