# Generated by Django 5.1.1 on 2024-09-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_favoriterecipe_shoppingrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'default_related_name': '%(class)ss', 'ordering': ('recipe',)},
        ),
        migrations.AlterModelOptions(
            name='shoppingrecipe',
            options={'default_related_name': '%(class)ss', 'ordering': ('recipe',)},
        ),
        migrations.RenameField(
            model_name='favoriterecipe',
            old_name='favorite_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingrecipe',
            old_name='shopping_recipe',
            new_name='recipe',
        ),
    ]
