# Generated by Django 5.1.1 on 2024-09-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('author',), 'verbose_name': 'подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribed_to',
            new_name='author',
        ),
    ]
